/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.uweandapp.MySysScan3;

public final class R {
    public static final class attr {
    }
    public static final class color {
        /**  Retrieved via Resources.getColor() and friends. 
         */
        public static final int red=0x7f040000;
    }
    public static final class drawable {
        public static final int chip=0x7f020000;
        public static final int ic_menu_info_details=0x7f020001;
        public static final int logo=0x7f020002;
        public static final int logo_source=0x7f020003;
        public static final int myindicator=0x7f020004;
        /**  Retrieved via Resources.getDrawable() and friends. 
         */
        public static final int semi_black=0x7f020006;
        public static final int stat_notify_sync=0x7f020005;
    }
    public static final class id {
        public static final int action_info=0x7f080006;
        public static final int action_refresh=0x7f080005;
        public static final int cntListItem=0x7f080004;
        public static final int lblListHeader=0x7f080002;
        public static final int lblListItem=0x7f080003;
        public static final int lvExp=0x7f080001;
        public static final int mainWindow=0x7f080000;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int info_dialog=0x7f030001;
        public static final int list_group=0x7f030002;
        public static final int list_item=0x7f030003;
    }
    public static final class menu {
        public static final int menu_options=0x7f070000;
    }
    public static final class string {
        public static final int action_settings=0x7f050000;
        public static final int app_fullname=0x7f050001;
        public static final int app_name=0x7f050003;
        public static final int app_version=0x7f050002;
        public static final int author=0x7f050004;
        public static final int device=0x7f050005;
        public static final int main_app=0x7f050006;
    }
    public static final class style {
        /**  Define my custom ActionBar colors! 
         */
        public static final int MyActionBar=0x7f060001;
        public static final int MyAlertDialogStyle=0x7f060003;
        /** Doesn't work for some reason, always makes nested blocks in dialog, don't know why... 
<item name="android:alertDialogTheme">@style/MyAlertDialogStyle</item>
         */
        public static final int MyTheme=0x7f060000;
        public static final int MyTitleTextStyle=0x7f060002;
    }
}
